Resources:
  CloudFormationInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref CloudformationSG
      KeyName: cfkey
      ImageId: "ami-09e67e426f25ce0d7"
      InstanceType: "t2.micro"
      Tags:
        - Key: "Name"
          Value: "CF-instance"
  CloudformationSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "This SG is created by cloudformation"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "CF-SecurityGroup"
