Resources:
  CloudFormationInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref CloudformationSG
      KeyName: # Key-name
      ImageId: #Image Ids of the respective OS for ex. ami-123449
      InstanceType: "t2.micro" #ec2-instance types
      Tags:
        - Key: "Name"
          Value: "CF-instance"
  CloudformationSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "This SG is created by cloudformation"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "CF-SecurityGroup"
