Parameters:
  EC2ImageName:
    Description: "Enter OS type. Only Ubuntu20, Ubuntu18 and AMILinux are allowed"
    Type: String
    AllowedValues:
      - Ubuntu20
      - Ubuntu18
      - AMILinux
    Default: Ubuntu20
Mappings:
  ImageRef:
    AMILinux:
      "ImageId": #Image Ids of the respective OS for ex. ami-123449
    Ubuntu20:
      "ImageId": #Image Ids of the respective OS for ex. ami-123449
    Ubuntu18:
      "ImageId": #Image Ids of the respective OS for ex. ami-123449
Resources:
  CFInstance02:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref CFDemo2SG
      KeyName: #Key-name
      ImageId: !FindInMap [ImageRef, !Ref EC2ImageName, ImageId]
      InstanceType: "t2.micro" #ec2-instance type
      Tags:
        - Key: "Name"
          Value: "CF-demo-instance2"
  CFDemo2SG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "This SG is created by cloudformation"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "CF-demo-securityGroup2"
